### ISSUE TITLE
Duplicate name error

### ISSUE THREAD

**Issue by hshenmeow** [Yorag/wenku8-to-epub#1]
出现报错：
C:\Python312\Lib\zipfile\__init__.py:1607: UserWarning: Duplicate name: 'EPUB/Images/cover.jpg'
  return self._open_to_write(zinfo, force_zip64=force_zip64)
C:\Python312\Lib\zipfile\__init__.py:1607: UserWarning: Duplicate name: 'EPUB/cover.xhtml'
  return self._open_to_write(zinfo, force_zip64=force_zip64)
└── Packing volume completed

然后就无法输出epub文件

**Comment by Yorag** [comment]
book_id是多少，我这边测试一下

**Comment by hshenmeow** [comment]
> book_id是多少，我这边测试一下

1861
我试了其中的几卷都有这个问题

**Comment by Yorag** [comment]
> 因版权问题，文库不再提供该小说的阅读！

我这边看wenku8，这本小说没内容，确实下载不了。
至于这个报错，我稍后修复一下明确报错信息。

**Comment by hshenmeow** [comment]
> > 因版权问题，文库不再提供该小说的阅读！
> 
> 我这边看wenku8，这本小说没内容，确实下载不了。 至于这个报错，我稍后修复一下明确报错信息。

好的原来如此。不过其实用他家app还是可以看的，不知道后续是否可以优化一下这个问题，辛苦！

**Comment by Yorag** [comment]
请问app是哪个，我看官网上并没有给链接

**Comment by hshenmeow** [comment]
> 请问app是哪个，我看官网上并没有给链接

我这边是直接用安卓手机apkpure搜索“轻小说文库”就可以找到

**Comment by Yorag** [comment]
> > 请问app是哪个，我看官网上并没有给链接
> 
> 我这边是直接用安卓手机apkpure搜索“轻小说文库”就可以找到

好的，我后续了解一下
